import { Organization } from "@/types/organization";
import { BloodRequest } from "@/types/blood";
import { UserProfile } from "@/types/user";

export const MOCK_USER: UserProfile = {
  id: "usr_rohit",
  name: "Rohit Bramhe",
  email: "rohit@example.com",
  phone: "+91 9876543210",
  bloodGroup: "O+",
  city: "Nagpur",
  state: "Maharashtra",
  role: "recipient",
  isAvailableDonor: true,
  language: "en",
};

export const MOCK_ORGANIZATIONS: Organization[] = [
  {
    id: "org_gmch",
    name: "Government Medical College & Hospital",
    type: "Hospital",
    address: "Mahatma Gandhi Rd, Dhantoli, Nagpur, Maharashtra 440012",
    city: "Nagpur",
    state: "Maharashtra",
    distanceKm: 2.4,
    phone: "+91 712 245 6789",
    isVerified: true,
    isOpen24Hours: true,
    operatingHours: "Open 24 hours",
    lastUpdatedMinutesAgo: 12,
    latitude: 21.1345,
    longitude: 79.0825,
    inventory: {
      "O+": 8,
      "O-": 2,
      "A+": 6,
      "A-": 1,
      "B+": 7,
      "B-": 2,
      "AB+": 4,
      "AB-": 1,
    },
  },
  {
    id: "org_redcross",
    name: "Red Cross Blood Bank",
    type: "Blood Bank",
    address: "Civil Lines, Near High Court, Nagpur, Maharashtra 440001",
    city: "Nagpur",
    state: "Maharashtra",
    distanceKm: 3.1,
    phone: "+91 712 256 1234",
    isVerified: true,
    isOpen24Hours: true,
    operatingHours: "Open 24 hours",
    lastUpdatedMinutesAgo: 30,
    latitude: 21.1524,
    longitude: 79.0768,
    inventory: {
      "O+": 5,
      "O-": 1,
      "A+": 4,
      "A-": 0,
      "B+": 5,
      "B-": 1,
      "AB+": 2,
      "AB-": 0,
    },
  },
  {
    id: "org_lifecare",
    name: "LifeCare Hospital",
    type: "Hospital",
    address: "Wardha Rd, Somalwada, Nagpur, Maharashtra 440025",
    city: "Nagpur",
    state: "Maharashtra",
    distanceKm: 4.8,
    phone: "+91 712 278 9012",
    isVerified: false,
    isOpen24Hours: true,
    operatingHours: "Open 24 hours",
    lastUpdatedMinutesAgo: 60,
    latitude: 21.1021,
    longitude: 79.0684,
    inventory: {
      "O+": 2,
      "O-": 0,
      "A+": 3,
      "A-": 1,
      "B+": 3,
      "B-": 0,
      "AB+": 1,
      "AB-": 0,
    },
  },
  {
    id: "org_cityblood",
    name: "City Blood Bank",
    type: "Blood Bank",
    address: "Dharampeth, VIP Road, Nagpur, Maharashtra 440010",
    city: "Nagpur",
    state: "Maharashtra",
    distanceKm: 5.2,
    phone: "+91 712 253 4567",
    isVerified: true,
    isOpen24Hours: false,
    operatingHours: "8:00 AM - 10:00 PM",
    lastUpdatedMinutesAgo: 120,
    latitude: 21.1412,
    longitude: 79.0612,
    inventory: {
      "O+": 4,
      "O-": 2,
      "A+": 5,
      "A-": 2,
      "B+": 6,
      "B-": 1,
      "AB+": 3,
      "AB-": 1,
    },
  },
];

export const MOCK_REQUESTS: BloodRequest[] = [
  {
    id: "#BH20250915",
    patientName: "Amit Sharma",
    bloodGroup: "O+",
    units: 2,
    hospitalName: "Government Medical College & Hospital",
    hospitalAddress: "Dhantoli, Nagpur",
    isEmergency: true,
    contactPerson: "Rohit Sharma",
    contactPhone: "+91 9876543210",
    status: "Searching",
    createdAt: "Just now",
    organizationId: "org_gmch",
    organizationName: "Government Medical College & Hospital",
  },
  {
    id: "#BH20250910",
    patientName: "Sunita Verma",
    bloodGroup: "A+",
    units: 1,
    hospitalName: "Red Cross Blood Bank",
    hospitalAddress: "Civil Lines, Nagpur",
    isEmergency: false,
    contactPerson: "Rohit Bramhe",
    contactPhone: "+91 9876543210",
    status: "Accepted",
    createdAt: "2 days ago",
    organizationId: "org_redcross",
    organizationName: "Red Cross Blood Bank",
  },
  {
    id: "#BH20250905",
    patientName: "Kavita Patil",
    bloodGroup: "O+",
    units: 3,
    hospitalName: "LifeCare Hospital",
    hospitalAddress: "Wardha Rd, Nagpur",
    isEmergency: false,
    contactPerson: "Rohit Bramhe",
    contactPhone: "+91 9876543210",
    status: "Completed",
    createdAt: "5 days ago",
    organizationId: "org_lifecare",
    organizationName: "LifeCare Hospital",
  },
  {
    id: "#BH20250828",
    patientName: "Rajesh Kumar",
    bloodGroup: "B+",
    units: 1,
    hospitalName: "City Blood Bank",
    hospitalAddress: "Dharampeth, Nagpur",
    isEmergency: false,
    contactPerson: "Rohit Bramhe",
    contactPhone: "+91 9876543210",
    status: "Cancelled",
    createdAt: "10 days ago",
    organizationId: "org_cityblood",
    organizationName: "City Blood Bank",
  },
];
